### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by christyanbrayan** [christyanbrayan/batman-links#3]
- [ ] Add GIF on README
- [ ] Update  CSS
- [ ] Responsiveness
- [ ] Add more links and add href (?)
- [ ] Add text translations (?)
- [ ] Add minify files to GH Pages (change branch to deploy?)
- [ ] Add SEO tags and Google Analytics
